data_user = [
  {"username": "Acoblaren01", "password": "@Acob01Pass!"},
  {"username": "Brixton88", "password": "@Bri88Strong"},
  {"username": "CaldwellX", "password": "@CalX2025"},
  {"username": "DarianSky", "password": "@DarSky99"},
  {"username": "ElyraMoon", "password": "@ElyMoon77"},
  {"username": "FintanV", "password": "@FinV_123"},
  {"username": "GarrickQ", "password": "@GarQ!456"},
  {"username": "HavenLi", "password": "@HavLi789"},
  {"username": "IcarusZ", "password": "@IcarZ202"},
  {"username": "JovianP", "password": "@JovP!33"},
  {"username": "KaelStorm", "password": "@KaelS_88"},
  {"username": "LioraB", "password": "@LioB2023"},
  {"username": "MarekN", "password": "@MarN_99"},
  {"username": "NylaStar", "password": "@NylS!77"},
  {"username": "OrionF", "password": "@OriF_456"},
  {"username": "PaxtonD", "password": "@PaxD!88"},
  {"username": "QuintusR", "password": "@QuinR_21"},
  {"username": "RavynG", "password": "@RavG!55"},
  {"username": "SeleneH", "password": "@SelH_2025"},
  {"username": "TobiasK", "password": "@TobK_123"},
  {"username": "UlyssesM", "password": "@UlyM!88"},
  {"username": "VesperY", "password": "@VesY_99"},
  {"username": "WrenC", "password": "@WreC!456"},
  {"username": "XanderJ", "password": "@XanJ_77"},
  {"username": "YaraL", "password": "@YarL202"},
  {"username": "ZionF", "password": "@ZioF!33"},
  {"username": "AlaricT", "password": "@AlarT_88"},
  {"username": "BlytheV", "password": "@BlyV!99"},
  {"username": "CorwinP", "password": "@CorP_456"},
  {"username": "DaphneS", "password": "@DaphS_77"},
  {"username": "EmrysK", "password": "@EmrK2023"},
  {"username": "FayeN", "password": "@FayN!88"},
  {"username": "GideonR", "password": "@GidR_123"},
  {"username": "HalcyonL", "password": "@HalL!99"},
  {"username": "IsoldeQ", "password": "@IsoQ_2025"},
  {"username": "JarethM", "password": "@JarM!77"},
  {"username": "KieraX", "password": "@KieX_456"},
  {"username": "LucianD", "password": "@LucD_88"},
  {"username": "MorriganB", "password": "@MorB!99"},
  {"username": "NikolaiV", "password": "@NikV_123"},
  {"username": "OpheliaT", "password": "@OphT!77"},
  {"username": "PeregrineS", "password": "@PerS_202"},
  {"username": "QuorraJ", "password": "@QuoJ_88"},
  {"username": "RowanC", "password": "@RowC!99"},
  {"username": "SeraphineH", "password": "@SerH_123"},
  {"username": "TheronK", "password": "@TheK_77"},
  {"username": "UlricF", "password": "@UlrF!88"},
  {"username": "ValeriaD", "password": "@ValD_456"},
  {"username": "WystanB", "password": "@WysB_2025"},
  {"username": "XyliaN", "password": "@XylN!33"},
  {"username": "YorickP", "password": "@YorP_77"},
  {"username": "ZephyrG", "password": "@ZepG_88"},
  {"username": "ArdenV", "password": "@ArdV_123"},
  {"username": "BrionyL", "password": "@BriL!99"},
  {"username": "CaspianT", "password": "@CasT_77"},
  {"username": "DelphineM", "password": "@DelM!88"},
  {"username": "EamonQ", "password": "@EamQ_202"},
  {"username": "FreyaS", "password": "@FreS_123"},
  {"username": "GaladrielX", "password": "@GalX_99"},
  {"username": "HawthorneB", "password": "@HawB_88"},
  {"username": "IoneF", "password": "@IonF!77"},
  {"username": "JocelynK", "password": "@JocK_456"},
  {"username": "KaidaR", "password": "@KaiR!33"},
  {"username": "LysanderP", "password": "@LysP_88"},
  {"username": "MagnusV", "password": "@MagV_123"},
  {"username": "NerissaH", "password": "@NerH!77"},
  {"username": "OctavianC", "password": "@OctC_202"},
  {"username": "PersephoneD", "password": "@PerD_99"},
  {"username": "QuintellaF", "password": "@QuiF!88"},
  {"username": "RhiannonG", "password": "@RhiG_77"},
  {"username": "SylasJ", "password": "@SylJ_456"},
  {"username": "TamsinL", "password": "@TamL_2025"},
  {"username": "UrsulaM", "password": "@UrsM!33"},
  {"username": "VincenzoN", "password": "@VinN_88"},
  {"username": "WaverlyO", "password": "@WavO_123"},
  {"username": "XantheP", "password": "@XanP!77"},
  {"username": "YvetteQ", "password": "@YveQ_99"},
  {"username": "ZephyrusR", "password": "@ZepR_202"},
  {"username": "AureliaS", "password": "@AurS_88"},
  {"username": "BalthazarT", "password": "@BalT_123"},
  {"username": "CelesteU", "password": "@CelU!77"},
  {"username": "DimitriV", "password": "@DimV_456"},
  {"username": "ElowenW", "password": "@ElwW_2025"},
  {"username": "FinnianX", "password": "@FinX!33"},
  {"username": "GwendolynY", "password": "@GweY_88"},
  {"username": "HectorZ", "password": "@HecZ_123"},
  {"username": "IsadoraA", "password": "@IsaA!77"},
  {"username": "JuliusB", "password": "@JulB_99"},
  {"username": "KallistaC", "password": "@KalC_202"},
  {"username": "LeanderD", "password": "@LeaD_88"},
  {"username": "MirabelE", "password": "@MirE_123"},
  {"username": "NikolinaF", "password": "@NikF!77"},
  {"username": "OberonG", "password": "@ObeG_456"},
  {"username": "PetronellaH", "password": "@PetH_2025"},
  {"username": "QuintinI", "password": "@QuiI!33"},
  {"username": "RaphaelJ", "password": "@RapJ_88"},
  {"username": "SelahK", "password": "@SelK_123"},
  {"username": "ThaddeusL", "password": "@ThadL_77"},
  {"username": "UrijahM", "password": "@UriM_99"},
  {"username": "ValentineN", "password": "@ValN_202"},
  {"username": "WilhelminaO", "password": "@WilO!88"},
  {"username": "XimenaP", "password": "@XimP_123"},
  {"username": "YorandaQ", "password": "@YorQ_77"},
  {"username": "ZephinaR", "password": "@ZepR_456"},
  {"username": "AelianaS", "password": "@AelS_2025"},
  {"username": "BenedictT", "password": "@BenT!33"},
  {"username": "CressidaU", "password": "@CreU_88"},
  {"username": "DorianV", "password": "@DorV_123"},
  {"username": "EvanderW", "password": "@EvaW!77"},
  {"username": "FaelanX", "password": "@FaeX_99"},
  {"username": "GalateaY", "password": "@GalY_202"},
  {"username": "HadrianZ", "password": "@HadZ_88"},
  {"username": "IsabeauA", "password": "@IsaA_123"},
  {"username": "JovianneB", "password": "@JovB!77"},
  {"username": "KieranC", "password": "@KieC_456"},
  {"username": "LucindaD", "password": "@LucD_2025"},
  {"username": "MontagueE", "password": "@MonE!33"},
  {"username": "NathaliaF", "password": "@NatF_88"},
  {"username": "OctaviaG", "password": "@OctG_123"},
  {"username": "PhineasH", "password": "@PhiH_77"},
  {"username": "QuenbyI", "password": "@QueI!99"},
  {"username": "RaphaelaJ", "password": "@RapJ_202"},
  {"username": "SelwynK", "password": "@SelK_88"},
  {"username": "ThalassaL", "password": "@ThaL_123"},
  {"username": "UlaniM", "password": "@UlaM!77"},
  {"username": "VanyaN", "password": "@VanN_456"},
  {"username": "WilfredO", "password": "@WilO_2025"},
  {"username": "XaviaP", "password": "@XavP!33"},
  {"username": "YulianaQ", "password": "@YulQ_88"},
  {"username": "ZaharaR", "password": "@ZahR_123"},
  {"username": "AldricH", "password": "@AldH123!"},
  {"username": "BranwenT", "password": "@BranT456#"},
  {"username": "CassianL", "password": "@CasL789$"},
  {"username": "DahliaF", "password": "@DahF321%"},
  {"username": "EryndorV", "password": "@EryV654&"},
  {"username": "FaelithS", "password": "@FaeS987*"},
  {"username": "GalenP", "password": "@GalP159^"},
  {"username": "HelenaQ", "password": "@HelQ753!"},
  {"username": "IlyasR", "password": "@IlyR852@"},
  {"username": "JorvanK", "password": "@JorK963$"},
  {"username": "KaelithM", "password": "@KaelM741%"},
  {"username": "LyannaB", "password": "@LyaB258&"},
  {"username": "MagnusC", "password": "@MagC369*"},
  {"username": "NerithD", "password": "@NerD147^"},
  {"username": "OrrinE", "password": "@OrrE852#"},
  {"username": "PerseF", "password": "@PerF963!"},
  {"username": "QuillonG", "password": "@QuiG741$"},
  {"username": "RhiarH", "password": "@RhiH258%"},
  {"username": "SylvaraI", "password": "@SylI369&"},
  {"username": "TheronJ", "password": "@TheJ147*"},
]

programs = [
    "BSIT",
    "BSCS",
    "BSIS",
    "BSECE",
    "BSEME",
    "BSECE-IT",
    "BSBA Marketing",
    "BSBA Finance",
    "BSBA HRM",
    "BSED Mathematics",
    "BSED English",
    "BSED Science",
    "AB Psychology",
    "AB Political Science",
    "AB Literature",
    "BS Nursing",
    "BS Midwifery",
    "BS Hospitality Management",
    "BS Tourism Management",
    "BSEd Early Childhood Education",
    "BS Accountancy",
    "BSA Economics",
    "BSA Statistics",
    "BSA Information Systems",
    "BS Architecture",
    "BS Civil Engineering",
    "BS Mechanical Engineering",
    "BS Electrical Engineering",
    "BS Electronics Engineering",
    "BS Industrial Engineering",
    "BSc Applied Mathematics",
    "BSc Biology",
    "BSc Chemistry",
    "BSc Physics",
    "BA Communication",
    "BA English",
    "BA History",
    "BA Political Science",
    "BA Philosophy",
    "BA Sociology",
    "BA Anthropology",
    "BFA Fine Arts",
    "BM Music",
    "BMM Multimedia Arts"
]
